---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-cert-manager-agent-sa
  namespace: nginx-cert-manager # Ensure this matches the deployment namespace

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: domaincertificate-editor
  namespace: nginx-cert-manager # Ensure this matches the deployment namespace
rules:
- apiGroups: ["cert.nginx.io"] # The API group of your CRD
  resources: ["domaincertificates", "domaincertificates/status"] # The plural name of your CRD and its status subresource
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # Permissions needed
- apiGroups: [""] # Core API group
  resources: ["secrets"] # Permission for secrets
  # Limit verbs if possible, e.g., only get/create/update if delete isn't needed
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-cert-manager-agent-rb
  namespace: nginx-cert-manager # Ensure this matches the deployment namespace
subjects:
- kind: ServiceAccount
  name: nginx-cert-manager-agent-sa # Name of the ServiceAccount created above
  namespace: nginx-cert-manager # Namespace of the ServiceAccount
roleRef:
  kind: Role
  name: domaincertificate-editor # Name of the Role created above
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-config-editor # New ClusterRole for webhook config
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  resourceNames: ["domaincertificate-validation-webhook"] # Restrict to the specific webhook config
  verbs: ["get", "update", "patch"] # Limit verbs

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-cert-manager-agent-webhook-crb # New ClusterRoleBinding
subjects:
- kind: ServiceAccount
  name: nginx-cert-manager-agent-sa # ServiceAccount name
  namespace: nginx-cert-manager # Namespace of the ServiceAccount
roleRef:
  kind: ClusterRole
  name: webhook-config-editor # Reference the new ClusterRole
  apiGroup: rbac.authorization.k8s.io
