# Placeholder secret for webhook TLS certificate and key.
# Replace <base64-...> placeholders with actual base64 encoded data.
# Use 'kubectl create secret tls webhook-tls-secret --cert=path/to/tls.crt --key=path/to/tls.key -n default --dry-run=client -o yaml'
# or base64 encode your files manually.
apiVersion: v1
type: kubernetes.io/tls
kind: Secret
metadata:
  name: webhook-tls-secret
  namespace: nginx-cert-manager
data:
  tls.crt: Cg==
  tls.key: Cg==
