apiVersion: batch/v1
kind: Job
metadata:
  # Name of the Job
  name: setup-secrets-job
  # Namespace where the job will run (should match the agent)
  namespace: nginx-cert-manager
  labels:
    # Label for the Job itself
    app: setup-secrets-job
spec:
  template:
    metadata:
      labels:
        # Labels applied to the Pods created by this Job
        app: setup-secrets-job
    spec:
      # Use the same Service Account as the agent deployment for API access
      serviceAccountName: nginx-cert-manager-agent-sa
      containers:
      # Container to run the setup script for secrets
      - name: setup-secrets
        image: registry.asean-accesstrade.net/library/nginx-cert-manager:latest
        imagePullPolicy: Always
        # Command to execute the init script
        command: ["python", "/app/utils/init.py"]
        env:
          # Pass the namespace to the script using the Downward API
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          # Pass the webhook service name (adjust if needed)
          - name: WEBHOOK_SERVICE_NAME
            value: "webhook-service"
          # Ensure Python output isn't buffered
          - name: PYTHONUNBUFFERED
            value: "1"
      # Restart policy for the Job Pod
      restartPolicy: Never # Or OnFailure, depending on desired behavior
  # Optional: Control how long the Job and its Pods are kept after completion
  # ttlSecondsAfterFinished: 3600 # Keep for 1 hour
  # backoffLimit: 4 # Number of retries before marking the Job as failed
