# Placeholder secret for agent configuration (RabbitMQ, AWS).
# Replace <base64-...> placeholders with actual base64 encoded data.
# Use 'kubectl create secret generic agent-secrets --from-literal=key=value ... -n default --dry-run=client -o yaml'
# or base64 encode your values manually.
apiVersion: v1
kind: Secret
metadata:
  name: agent-secrets
  namespace: nginx-cert-manager # Ensure this matches the deployment namespace
type: Opaque
data:
  # Base64 encoded value for RabbitMQ username
  rabbitmq_user: dXNlcg== # Placeholder for base64 encoded 'user'
  # Base64 encoded value for RabbitMQ password
  rabbitmq_password: cGFzc3dvcmQ= # Placeholder for base64 encoded 'password'
  # Base64 encoded value for AWS Access Key ID
  aws_access_key_id: QVNLSUExMjM0NTY3ODlBQkNERUY= # Placeholder for base64 encoded AWS Access Key ID
  # Base64 encoded value for AWS Secret Access Key
  aws_secret_access_key: d0phbHZ5RStMTk1hbGtqYXNkZmdoaWprbG1ub3BxcnN0dXZ3eHla # Placeholder for base64 encoded AWS Secret Access Key
  # Add other keys like S3 bucket name or SSH user if needed and base64 encoded
  # s3_bucket_name: <base64-encoded-bucket-name>
  # ssh_user: <base64-encoded-ssh-user>
