apiVersion: v1
kind: Service
metadata:
  name: rabbitmq # This name will be used as the DNS host name (rabbitmq.namespace.svc.cluster.local)
  namespace: nginx-cert-manager # Ensure this matches the deployment namespace
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq # Selects pods with the label app=rabbitmq
  ports:
  - name: amqp
    port: 5672      # Port the service listens on
    targetPort: 5672 # Port the pods listen on (from the deployment)
    protocol: TCP
  - name: management
    port: 15672     # Port for the management UI
    targetPort: 15672
    protocol: TCP
  type: ClusterIP # Expose the service only within the cluster
