# Placeholder secret for the SSH private key.
# Replace <base64-...> placeholder with actual base64 encoded data.
# Use 'kubectl create secret generic ssh-key-secret --from-file=key.pem=/path/to/your/ssh_private_key.pem -n default --dry-run=client -o yaml'
# or base64 encode your file manually.
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key-secret
  namespace: default # Ensure this matches the deployment namespace
type: Opaque
data:
  # Key name MUST be 'key.pem' to match the deployment volumeMount item path
  key.pem: Cg== # Placeholder for base64 encoded SSH private key (echo -n "" | base64)
