apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: domaincertificate-validation-webhook
webhooks:
  - name: validate.domaincertificate.cert.nginx.io
    rules:
      - apiGroups: ["cert.nginx.io"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["domaincertificates"]
        scope: "Namespaced"
    clientConfig:
      # Replace 'nginx-cert-manager-agent' and 'default' with the actual
      # service name and namespace where your agent is running.
      service:
        name: nginx-cert-manager-agent # Name of the service running the agent
        namespace: default             # Namespace of the service
        path: "/admission/validate"    # The new endpoint in http_agent.py
        port: 443                      # Webhooks MUST use HTTPS
      # caBundle: MUST be provided. Base64-encoded CA certificate bundle to verify
      # the webhook server's certificate. cert-manager can inject this automatically.
      # caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5 # Keep timeout short
