# Placeholder secret for webhook TLS certificate and key.
# Replace <base64-...> placeholders with actual base64 encoded data.
# Use 'kubectl create secret tls webhook-tls-secret --cert=path/to/tls.crt --key=path/to/tls.key -n default --dry-run=client -o yaml'
# or base64 encode your files manually.
apiVersion: v1
kind: Secret
metadata:
  name: webhook-tls-secret
  namespace: nginx-cert-manager # Ensure this matches the deployment namespace
type: kubernetes.io/tls
data:
  tls.crt: Cg== # Placeholder for base64 encoded tls.crt (echo -n "" | base64)
  tls.key: Cg== # Placeholder for base64 encoded tls.key (echo -n "" | base64)
