apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: domaincertificates.cert.nginx.io
spec:
  group: cert.nginx.io
  versions:
    - name: v1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]
          properties:
            spec:
              type: object
              required: ["domain", "email", "dnsProvider"]
              properties:
                domain:
                  type: string
                  description: "The domain name for which to issue the certificate"
                email:
                  type: string
                  description: "Email address for certificate notifications"
                autoRenewal:
                  type: boolean
                  description: "Whether to automatically renew certificates before expiration"
                dnsProvider:
                  type: string
                  description: "DNS provider used for DNS-01 challenge (e.g., cloudflare, route53)"
                nginxConfigs:
                  type: array
                  description: "List of NGINX configurations where the certificate should be deployed"
                  items:
                    type: object
                    required: ["server", "configPath", "certPath"]
                    properties:
                      server:
                        type: string
                        description: "Identifier for the NGINX server"
                      configPath:
                        type: string
                        description: "Path to the NGINX configuration file"
                      certPath:
                        type: string
                        description: "Path where certificates should be stored"
                      vhost:
                        type: string
                        description: "Virtual host name"
                      instanceIp:
                        type: string
                        description: "IP address of the NGINX instance"
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    required: ["type", "status"]
                    properties:
                      type:
                        type: string
                        description: "Type of the condition (Ready, Processing, Error)"
                      status:
                        type: string
                        description: "Status of the condition (True, False, Unknown)"
                      reason:
                        type: string
                        description: "Reason for the condition's last transition"
                      message:
                        type: string
                        description: "Human-readable message indicating details about the transition"
                      lastTransitionTime:
                        type: string
                        format: date-time
                        description: "Last time the condition transitioned from one status to another"
                state:
                  type: string
                  description: "Current state of the certificate (Pending, Issued, Error, Renewing)"
                notBefore:
                  type: string
                  format: date-time
                  description: "Certificate validity start timestamp"
                notAfter:
                  type: string
                  format: date-time
                  description: "Certificate expiration timestamp"
                serialNumber:
                  type: string
                  description: "Certificate serial number"
                lastRenewalTime:
                  type: string
                  format: date-time
                  description: "Last time the certificate was renewed"
                deployedTo:
                  type: array
                  description: "List of NGINX servers where the certificate deployment was attempted"
                  items:
                    type: object
                    properties:
                      server:
                        type: string
                        description: "NGINX server identifier (e.g., IP address)"
                      deployTime:
                        type: string
                        format: date-time
                        description: "Time when deployment attempt was made to this server"
                      status:
                        type: string
                        description: "Deployment status (Success, Failed)"
                      error:
                        type: string
                        description: "Error message if deployment failed"
      additionalPrinterColumns:
      - name: Domain
        type: string
        jsonPath: .spec.domain
      - name: Status
        type: string
        jsonPath: .status.state
      - name: Expires
        type: string
        jsonPath: .status.notAfter
      - name: Auto-Renewal
        type: boolean
        jsonPath: .spec.autoRenewal
      - name: DNS Provider
        type: string
        jsonPath: .spec.dnsProvider
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: domaincertificates
    singular: domaincertificate
    kind: DomainCertificate
    shortNames:
    - domcert
